name: firetiger
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider:
  dio:
  fluttertoast:
  flutter_screenutil:
  shared_preferences:
  flutter_swiper:
  transparent_image:                              # 网络图片过渡
  image_picker:                                   # 选择图片和视频
  image_cropper:                                  # 裁剪图片
  fijkplayer:                                     # 视频播放器
  flutter_cupertino_date_picker:                  # 日期选择器
  city_pickers:
  flutter_html:
  share:
  event_bus:
  like_button:                                    # 点赞动画
  fl_chart:                                       # 数据图表
  percent_indicator:                              # 圆形数据表
  webview_flutter:                                
  pull_to_refresh:                                # 下拉刷新上拉加载
  rongcloud_im_plugin:
  convex_bottom_bar:                              # 底部bottom切换动画
  # scroll_bottom_navigation_bar:                   # 滚动时隐藏tab动画


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/tag1.png
    - assets/images/tag2.png
    - assets/images/tag3.png
    - assets/images/tag4.png
    - assets/images/tag5.png
    - assets/images/xx.png
    - assets/images/dj.png
    - assets/images/lw.png
    - assets/images/wd.png
    - assets/images/banner.png
    - assets/images/huohuan.png
    - assets/images/award.png
    - assets/images/shop.png
    - assets/images/wallet.png
    - assets/images/order.png
    - assets/images/gz.png
    - assets/images/jc.png
    - assets/images/qb.png
    - assets/images/sp.png
    - assets/images/sz.png
    - assets/images/bz.png
    - assets/images/bzb.png
    - assets/images/gift.png
    - assets/images/comments.png
    - assets/images/hj.png
    - assets/images/jb.png
    - assets/images/lwh.png
    - assets/images/jb2.png
    - assets/images/address.png
    - assets/images/over.png
    - assets/images/time.png
    - assets/images/live.png
    - assets/images/nofollow.png
    - assets/images/basketball.png
    - assets/images/footballball.png
    - assets/images/videoGame.png
    - assets/images/golf.png
    - assets/images/gj.png
    - assets/images/jj.png
    - assets/images/yj.png
    - assets/images/ranking-1.png
    - assets/images/ranking-2.png
    - assets/images/ranking-3.png
    - assets/images/ranking-other.png
    - assets/images/hd.png
    - assets/images/pay.png
    - assets/images/livelw.png
    - assets/images/jg.png
    - assets/images/redP.png
    - assets/images/yellowP.png
    - assets/images/pennant.png
    - assets/images/dy.png
    - assets/images/MatchHeader.png
    - assets/images/bkb.png
    - assets/images/fb.png
    - assets/images/vd.png
    - assets/images/vs.png
    - assets/images/home.png
    - assets/images/like.png
    - assets/images/live_nor.png
    - assets/images/expert.png
    - assets/images/game.png
    - assets/images/home_lable.png
    - assets/images/like_lable.png
    - assets/images/live_lable.png
    - assets/images/expert_lable.png
    - assets/images/game_lable.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: myIcon
      fonts:
        - asset: assets/font/iconfont.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
